on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt get update
        sudo apt install -y gcc-10-riscv64-linux-gnu g++-10-riscv64-linux-gnu
